# See: https://docs.github.com/en/actions/writing-workflows
---
name: Release

# Trigger on any tag creation:
on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            artifact: linux-x86
            target: x86_64-unknown-linux-gnu
            strip: true
          - os: ubuntu-latest
            artifact: linux-arm
            target: aarch64-unknown-linux-gnu
            use-zigbuild: true
          - os: ubuntu-latest
            artifact: macos-x86
            target: x86_64-apple-darwin
            use-zigbuild: true
          - os: ubuntu-latest
            artifact: macos-arm
            target: aarch64-apple-darwin
            use-zigbuild: true
          - os: ubuntu-latest
            artifact: windows-x64
            target: x86_64-pc-windows-gnu
            extension: exe
    name: Build ${{ matrix.artifact }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - name: Build
        uses: AsimovPlatform/build-rust-action@v1
        with:
          target: ${{ matrix.target }}
          artifact-name: ${{ matrix.artifact }}
          binary-extension: ${{ matrix.extension }}
          strip-artifact: ${{ matrix.strip || 'false' }}
          use-zigbuild: ${{ matrix.use-zigbuild || 'false' }}
          rust-toolchain: 1.81.0

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: AsimovPlatform/release-action@v1
        with:
          changelog-path: CHANGES.md
